/** Server component: the event QR as a print-ready white card with black
 *  code (maximum scan contrast on posters) + the join link. */
import QRCode from "qrcode";

export async function QrPanel({ joinUrl }: { joinUrl: string }) {
  const svg = await QRCode.toString(joinUrl, {
    type: "svg",
    margin: 0,
    width: 168,
    color: { dark: "#000000", light: "#ffffff" },
  });

  return (
    <section className="border border-white/10 p-6">
      <h2 className="text-sm font-semibold tracking-[0.2em] text-white/50 uppercase">
        Attendee QR
      </h2>
      <p className="mt-1 text-sm text-white/40">
        Scan → selfie → personal gallery. Print it, hang it at the venue.
      </p>
      <div className="mt-5 flex items-center gap-6">
        <div
          className="shrink-0 bg-white p-4"
          // Trusted content: generated by us from our own URL.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div className="min-w-0">
          <p className="text-xs tracking-[0.2em] text-white/40 uppercase">Join link</p>
          <p className="mt-1 break-all font-mono text-sm text-white/80">{joinUrl}</p>
        </div>
      </div>
    </section>
  );
}
