/** Server component: renders the event QR as inline SVG + the join link.
 *  Print the QR, hang it at the venue — that's the whole attendee funnel. */
import QRCode from "qrcode";

export async function QrPanel({ joinUrl }: { joinUrl: string }) {
  const svg = await QRCode.toString(joinUrl, {
    type: "svg",
    margin: 1,
    width: 180,
    color: { dark: "#10b981", light: "#00000000" },
  });

  return (
    <section className="rounded-xl border border-zinc-800 p-5">
      <h2 className="text-lg font-semibold">Attendee QR code</h2>
      <p className="text-sm text-zinc-400">
        Attendees scan this → selfie → their personal gallery.
      </p>
      <div className="mt-4 flex items-center gap-6">
        <div
          className="shrink-0 rounded-lg bg-zinc-900 p-3"
          // Trusted content: generated by us from our own URL.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div className="min-w-0">
          <p className="text-xs text-zinc-500 uppercase tracking-wide">Join link</p>
          <p className="mt-1 break-all font-mono text-sm text-zinc-300">{joinUrl}</p>
          <p className="mt-3 text-xs text-zinc-500">
            Testing with your phone? The link must use your Mac's LAN IP, not
            localhost — set NEXT_PUBLIC_APP_URL in .env.
          </p>
        </div>
      </div>
    </section>
  );
}
